export const SIGNAL_GROUPS = [
  { id: "Value",       color: "text-amber-400",   bg: "bg-amber-500/10 border-amber-500/20",   hex: "#f59e0b" },
  { id: "Form",        color: "text-emerald-400", bg: "bg-emerald-500/10 border-emerald-500/20", hex: "#10b981" },
  { id: "Consistency", color: "text-sky-400",     bg: "bg-sky-500/10 border-sky-500/20",       hex: "#38bdf8" },
  { id: "Role",        color: "text-blue-400",    bg: "bg-blue-500/10 border-blue-500/20",      hex: "#60a5fa" },
  { id: "Matchup",     color: "text-teal-400",    bg: "bg-teal-500/10 border-teal-500/20",      hex: "#2dd4bf" },
  { id: "Meta",        color: "text-rose-400",    bg: "bg-rose-500/10 border-rose-500/20",      hex: "#fb7185" },
];

export const SIGNAL_CATEGORY_MAP: Record<string, string> = {
  underpriced_elite:     "Value",
  underpriced_mid:       "Value",
  overpriced_trap:       "Value",
  value_spike:           "Value",
  value_drop:            "Value",
  premium_value:         "Value",
  cash_cow:              "Value",
  price_cliff:           "Value",
  form_hot:              "Form",
  form_cold:             "Form",
  ceiling_spike:         "Form",
  floor_drop:            "Form",
  volatility_high:       "Form",
  elite_ceiling:         "Form",
  floor_lock:            "Form",
  ultra_consistent:      "Consistency",
  inconsistent:          "Consistency",
  trend_up:              "Consistency",
  trend_down:            "Consistency",
  high_floor_consistent: "Consistency",
  boom_bust:             "Consistency",
  role_improved:         "Role",
  role_declined:         "Role",
  midfield_boost:        "Role",
  role_uncertain:        "Role",
  premium_role:          "Role",
  fringe_risk:           "Role",
  easy_matchup:          "Matchup",
  hard_matchup:          "Matchup",
  tag_risk:              "Matchup",
  venue_boost:           "Matchup",
  neutral_matchup:       "Matchup",
  captain_viable:        "Meta",
  pod_play:              "Meta",
  high_ownership_risk:   "Meta",
  breakout_candidate:    "Meta",
  regression_candidate:  "Meta",
  player_out:            "Meta",
};

export const SIGNAL_PILLS_BY_GROUP: { group: string; signals: { id: string; label: string }[] }[] = [
  {
    group: "Value",
    signals: [
      { id: "underpriced_elite", label: "Underpriced Elite" },
      { id: "underpriced_mid",   label: "Underpriced Mid" },
      { id: "overpriced_trap",   label: "Overpriced Trap" },
      { id: "value_spike",       label: "Value Spike" },
      { id: "value_drop",        label: "Value Drop" },
      { id: "premium_value",     label: "Premium Value" },
      { id: "cash_cow",          label: "Cash Cow" },
      { id: "price_cliff",       label: "Price Cliff" },
    ],
  },
  {
    group: "Form",
    signals: [
      { id: "form_hot",        label: "Form Hot" },
      { id: "form_cold",       label: "Form Cold" },
      { id: "ceiling_spike",   label: "Ceiling Spike" },
      { id: "floor_drop",      label: "Floor Drop" },
      { id: "volatility_high", label: "Volatile" },
      { id: "elite_ceiling",   label: "Elite Ceiling" },
      { id: "floor_lock",      label: "Floor Lock" },
    ],
  },
  {
    group: "Consistency",
    signals: [
      { id: "ultra_consistent",      label: "Ultra Consistent" },
      { id: "inconsistent",          label: "Inconsistent" },
      { id: "trend_up",              label: "Trending Up" },
      { id: "trend_down",            label: "Trending Down" },
      { id: "high_floor_consistent", label: "High Floor" },
      { id: "boom_bust",             label: "Boom/Bust" },
    ],
  },
  {
    group: "Role",
    signals: [
      { id: "role_improved",  label: "Role Improved" },
      { id: "role_declined",  label: "Role Declined" },
      { id: "midfield_boost", label: "Midfield Boost" },
      { id: "role_uncertain", label: "Role Uncertain" },
      { id: "premium_role",   label: "Premium Role" },
      { id: "fringe_risk",    label: "Fringe Risk" },
    ],
  },
  {
    group: "Matchup",
    signals: [
      { id: "easy_matchup",    label: "Easy Matchup" },
      { id: "hard_matchup",    label: "Hard Matchup" },
      { id: "tag_risk",        label: "Tag Risk" },
      { id: "venue_boost",     label: "Venue Boost" },
      { id: "neutral_matchup", label: "Neutral" },
    ],
  },
  {
    group: "Meta",
    signals: [
      { id: "captain_viable",       label: "Captain Picks" },
      { id: "pod_play",             label: "POD Plays" },
      { id: "high_ownership_risk",  label: "High Ownership Fade" },
      { id: "breakout_candidate",   label: "Breakout Candidates" },
      { id: "regression_candidate", label: "Regression Watch" },
      { id: "player_out",           label: "Player Out" },
    ],
  },
];
