import { useEffect, useState } from "react";
import { Link } from "react-router-dom";
import {
  Crown, ArrowRight, Star, TrendingUp,
  TriangleAlert as AlertTriangle, Check, Database,
  Cpu, Radio, Trophy, Users, ChartBar as BarChart2,
  Lock, Target, ChartLine as LineChart, Shield, Zap,
  Sparkles, ToggleRight,
} from "lucide-react";
import { supabase } from "@/lib/supabaseClient";
import { useAuth } from "@/lib/auth";
import { NEEKO_PRICING } from "@/config/neekoPricing";
import MobileUpgradeBar from "@/components/mobile/MobileUpgradeBar";
import { LandingMarketWatchSample } from "@/components/landing/LandingMarketWatchSample";

// ─── Types ────────────────────────────────────────────────────────────────────

interface RankingRow {
  player_id: number;
  player_name: string;
  team: string | null;
  position: string | null;
  projection_final: number | null;
  ai_recommendation: string | null;
  summary_short: string | null;
  value_score: number | null;
  value_tag: string | null;
}

interface AccuracyExampleRow {
  player_name:   string;
  team_name:     string;
  projection:    number;
  actual_score:  number;
  error:         number;
  accuracy_tier: "ELITE" | "STRONG";
  round_label:   string;
  neeko_rank?:   number | null;
}

interface EdgeRow {
  player_id: number;
  player_name: string;
  team: string;
  position: string | null;
  projection_final: number | null;
  breakeven: number | null;
  edge_score: number | null;
  ai_recommendation: string | null;
  summary_short: string | null;
}

// ─── Static data ──────────────────────────────────────────────────────────────

const HOW_IT_WORKS = [
  {
    step: "01",
    icon: Database,
    title: "Historical AFL Data Modelling",
    desc: "Match data and player trends normalised into fantasy scoring metrics each round.",
  },
  {
    step: "02",
    icon: Cpu,
    title: "Projection Engine",
    desc: "Estimates scoring ranges, ceilings and volatility per player.",
  },
  {
    step: "03",
    icon: Radio,
    title: "Edge Signals Delivered",
    desc: "Captain picks, breakout alerts and trap warnings — ready before lockout.",
  },
];

const WHO_FOR = [
  {
    icon: Trophy,
    title: "Competitive League Players",
    desc: "Looking for captain edges and matchup advantages.",
  },
  {
    icon: BarChart2,
    title: "Data Driven Coaches",
    desc: "Prefer projections and metrics over guesswork.",
  },
  {
    icon: Users,
    title: "Fantasy Optimisers",
    desc: "Trying to maximise every lineup decision.",
  },
];

const NEEKO_FEATURES = [
  "Full projections",
  "Captain picks",
  "Breakout alerts",
  "Trade signals",
  "Advanced analytics",
  "AI player breakdowns",
  "Captain Edge Board",
  "Player vs Player comparison",
];

const FOOTER_LINKS = [
  { label: "Policies", to: "/policies" },
  { label: "Contact",  to: "/contact" },
  { label: "About",    to: "/about" },
  { label: "FAQ",      to: "/faq" },
];

const FEATURE_CARDS = [
  {
    icon: LineChart,
    title: "Rankings",
    desc: "Identify the best AFL Fantasy picks each week using projections and matchup modelling.",
    link: "/sports/afl/rankings",
    cta: "View Rankings",
  },
  {
    icon: Sparkles,
    title: "Edge Board",
    desc: "Find captain edges, breakout players and trap warnings generated by the Neeko model.",
    link: "/sports/afl/edge-board",
    cta: "View Edge Board",
  },
  {
    icon: ToggleRight,
    title: "Start / Sit",
    desc: "Compare players head-to-head using projections, volatility and matchup strength.",
    link: "/sports/afl/start-sit",
    cta: "View Start / Sit",
  },
  {
    icon: TrendingUp,
    title: "Market Watch",
    desc: "Spot underpriced players before the market reacts.",
    link: "/sports/afl/market-watch",
    cta: "View Market Watch",
  },
];

const WHY_NEEKO_BLOCKS = [
  {
    icon: Shield,
    title: "Opponent Adjusted Projections",
    desc: "Projections adjusted for matchup difficulty every round.",
  },
  {
    icon: AlertTriangle,
    title: "Volatility & Risk Modelling",
    desc: "Flags safe picks and high-variance players each week.",
  },
  {
    icon: Zap,
    title: "Market Value Detection",
    desc: "Detects underpriced players before the market reacts.",
  },
  {
    icon: Cpu,
    title: "AI Player Analysis",
    desc: "Plain-English insights explaining each projection and pick.",
  },
];

// ─── Shared layout ────────────────────────────────────────────────────────────

function SectionLabel({ children }: { children: string }) {
  return (
    <p className="text-center text-[11px] text-white/25 uppercase tracking-[0.18em] font-semibold mb-3">
      {children}
    </p>
  );
}

function SectionHeading({ children }: { children: React.ReactNode }) {
  return (
    <h2 className="text-2xl md:text-4xl font-extrabold text-white text-center leading-tight mb-3">
      {children}
    </h2>
  );
}

function GoldDivider() {
  return (
    <div className="flex justify-center my-4">
      <div className="w-10 h-0.5 rounded-full bg-[#F5C84C]/30" />
    </div>
  );
}

// ─── Feature Cards ────────────────────────────────────────────────────────────

function FeatureCards() {
  return (
    <section className="py-10 md:py-14 bg-[#070707] border-t border-white/[0.05]">
      <div className="max-w-5xl mx-auto px-4">
        <div className="text-center mb-8">
          <SectionLabel>Product Toolkit</SectionLabel>
          <SectionHeading>Your Weekly AFL Fantasy Toolkit</SectionHeading>
          <GoldDivider />
          <p className="text-sm text-white/40 max-w-lg mx-auto leading-relaxed">
            Everything you need each week to make smarter AFL Fantasy decisions.
          </p>
        </div>

        <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-6">
          {FEATURE_CARDS.map(({ icon: Icon, title, desc, link, cta }) => (
            <Link
              key={title}
              to={link}
              className="group flex flex-col bg-[#0f0f0f] border border-[#1f1f1f] rounded-xl p-6 transition-all hover:border-[#F5C84C] hover:shadow-[0_0_24px_rgba(245,200,76,0.12)] hover:scale-[1.02] focus:outline-none focus:ring-2 focus:ring-[#F5C84C]/50"
            >
              <div className="w-10 h-10 rounded-xl bg-[#F5C84C]/10 border border-[#F5C84C]/20 flex items-center justify-center mb-4 shrink-0">
                <Icon size={18} className="text-[#F5C84C]" />
              </div>
              <h3 className="text-base font-bold text-white leading-snug mb-2">{title}</h3>
              <p className="text-sm text-white/40 leading-relaxed flex-1 mb-5">{desc}</p>
              <span className="inline-flex items-center gap-1.5 text-xs font-semibold text-[#F5C84C]/70 group-hover:text-[#F5C84C] transition-colors">
                {cta}
                <ArrowRight size={12} />
              </span>
            </Link>
          ))}
        </div>
      </div>
    </section>
  );
}

// ─── Helpers ──────────────────────────────────────────────────────────────────

function teamAbbr(team: string) {
  const map: Record<string, string> = {
    "Adelaide": "ADE", "Brisbane Lions": "BRL", "Carlton": "CAR",
    "Collingwood": "COL", "Essendon": "ESS", "Fremantle": "FRE",
    "Geelong": "GEE", "Gold Coast": "GCS", "Greater Western Sydney": "GWS",
    "Hawthorn": "HAW", "Melbourne": "MEL", "North Melbourne": "NME",
    "Port Adelaide": "PAD", "Richmond": "RIC", "St Kilda": "STK",
    "Sydney": "SYD", "West Coast": "WCE", "Western Bulldogs": "WBD",
  };
  return map[team] ?? team.slice(0, 3).toUpperCase();
}

// ─── Model Accuracy ───────────────────────────────────────────────────────────

function formatRelativeTime(isoString: string | null): string | null {
  if (!isoString) return null;
  const diff = Date.now() - new Date(isoString).getTime();
  const mins  = Math.floor(diff / 60_000);
  const hours = Math.floor(diff / 3_600_000);
  const days  = Math.floor(diff / 86_400_000);
  if (mins < 2)   return "just now";
  if (mins < 60)  return `${mins} minutes ago`;
  if (hours < 24) return `${hours} hour${hours === 1 ? "" : "s"} ago`;
  return `${days} day${days === 1 ? "" : "s"} ago`;
}

interface AccuracyRow {
  players_analysed: number | null;
  avg_error: number | null;
  median_error: number | null;
  within_10: number | null;
  within_15: number | null;
  within_20: number | null;
  latest_round: number | null;
  total_predictions: number | null;
  last_updated_at: string | null;
  source: string | null;
}

function confidenceLevel(err: number | null): { label: string; color: string; bg: string; border: string; barColor: string } {
  if (err == null) return { label: "—",        color: "text-white/30",    bg: "bg-white/5",         border: "border-white/10",         barColor: "bg-white/20" };
  if (err < 16)    return { label: "ELITE",     color: "text-green-400",   bg: "bg-green-400/10",    border: "border-green-400/30",     barColor: "bg-green-400" };
  if (err <= 18)   return { label: "STRONG",    color: "text-[#F5C84C]",   bg: "bg-[#F5C84C]/10",    border: "border-[#F5C84C]/30",     barColor: "bg-[#F5C84C]" };
  return             { label: "MODERATE",       color: "text-red-400",     bg: "bg-red-400/10",      border: "border-red-400/30",       barColor: "bg-red-400" };
}

function reliabilityLevel(err: number | null): { label: string; color: string; bg: string; border: string } {
  if (err == null) return { label: "—",        color: "text-white/30",   bg: "bg-white/5",        border: "border-white/10" };
  if (err <= 16)   return { label: "ELITE",    color: "text-green-400",  bg: "bg-green-400/10",   border: "border-green-400/30" };
  if (err <= 18)   return { label: "STRONG",   color: "text-[#F5C84C]",  bg: "bg-[#F5C84C]/10",   border: "border-[#F5C84C]/30" };
  return             { label: "MODERATE",      color: "text-orange-400",  bg: "bg-orange-400/10",  border: "border-orange-400/30" };
}

interface DistBand {
  label: string;
  pct: number;
  color: string;
  bg: string;
}

function buildDistribution(row: AccuracyRow): DistBand[] {
  const w10  = row.within_10  ?? 0;
  const w15  = row.within_15  ?? 0;
  const w20  = row.within_20  ?? 0;
  return [
    { label: "0 – 10 pts",  pct: Math.max(w10, 0),          color: "bg-green-400",    bg: "text-green-400" },
    { label: "10 – 15 pts", pct: Math.max(w15 - w10, 0),    color: "bg-[#F5C84C]",    bg: "text-[#F5C84C]" },
    { label: "15 – 20 pts", pct: Math.max(w20 - w15, 0),    color: "bg-orange-400",   bg: "text-orange-400" },
    { label: "20+ pts",     pct: Math.max(100 - w20, 0),    color: "bg-red-500/70",   bg: "text-red-400" },
  ];
}

function ErrorDistributionBlock({ row, loading }: { row: AccuracyRow | null; loading: boolean }) {
  const hasData = !loading && row != null && (row.players_analysed ?? 0) > 0;
  const rel     = reliabilityLevel(hasData ? (row?.avg_error ?? null) : null);
  const bands   = hasData && row ? buildDistribution(row) : [];

  return (
    <div className="rounded-2xl border border-white/[0.07] bg-[#0e0e0e] overflow-hidden">
      <div className="flex items-center justify-between gap-4 px-5 py-3 border-b border-white/[0.06] bg-[#0a0a0a] flex-wrap">
        <div className="flex items-center gap-2">
          <div className="w-6 h-6 rounded-lg flex items-center justify-center bg-white/[0.05] border border-white/[0.08]">
            <BarChart2 size={13} className="text-white/50" />
          </div>
          <span className="text-sm font-semibold text-neutral-300">
            Prediction Error Distribution
          </span>
        </div>
        {!loading && (
          <span className={`text-xs px-3 py-1 rounded-full border ${rel.bg} ${rel.border} ${rel.color}`}>
            Reliability: {rel.label}
          </span>
        )}
        {loading && <div className="h-6 w-36 bg-white/[0.06] rounded-full animate-pulse" />}
      </div>

      <div className="px-5 py-4 space-y-3">
        {loading && (
          <div className="space-y-3">
            {[1,2,3,4].map(i => (
              <div key={i} className="flex items-center gap-3">
                <div className="w-20 h-3 bg-white/[0.06] rounded animate-pulse shrink-0" />
                <div className="flex-1 h-2.5 bg-white/[0.06] rounded-full animate-pulse" />
                <div className="w-8 h-3 bg-white/[0.06] rounded animate-pulse shrink-0" />
              </div>
            ))}
          </div>
        )}

        {!loading && !hasData && (
          <p className="text-sm text-white/30 text-center py-2">
            Accuracy metrics will appear after the first completed match.
          </p>
        )}

        {!loading && hasData && bands.map(({ label, pct, color, bg }) => {
          const rounded = Math.round(pct);
          return (
            <div key={label} className="flex items-center gap-3 group">
              <span className="w-[72px] text-[11px] font-semibold text-white/40 shrink-0 tabular-nums">
                {label}
              </span>
              <div className="flex-1 h-2.5 bg-white/[0.05] rounded-full overflow-hidden">
                <div
                  className={`h-full rounded-full transition-all duration-700 ${color}`}
                  style={{ width: `${Math.min(rounded, 100)}%` }}
                />
              </div>
              <span className={`w-9 text-right text-[12px] font-bold tabular-nums shrink-0 ${bg}`}>
                {rounded}%
              </span>
            </div>
          );
        })}
      </div>

      <div className="px-5 pb-4">
        <p className="text-[12px] text-white/30 leading-relaxed">
          Most projections land within 10–15 points — a reliable weekly baseline for lineup decisions.
        </p>
      </div>
    </div>
  );
}

function AccuracyBar({ pct, barColor }: { pct: number | null; barColor: string }) {
  const width = pct != null ? Math.min(Math.max(Math.round(pct), 0), 100) : 0;
  return (
    <div className="mt-2 h-1 w-full rounded-full bg-white/[0.06] overflow-hidden">
      <div
        className={`h-full rounded-full transition-all duration-700 ${barColor}`}
        style={{ width: `${width}%` }}
      />
    </div>
  );
}

function ModelAccuracySection() {
  const [row, setRow]         = useState<AccuracyRow | null>(null);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    (async () => {
      const { data, error } = await supabase
        .from("v_projection_accuracy_homepage")
        .select("*")
        .maybeSingle();
      if (error) {
        console.warn("Accuracy data unavailable", error);
        setRow(null);
      } else {
        setRow(data as AccuracyRow | null);
      }
      setLoading(false);
    })();
  }, []);

  const hasData = !loading && row != null && (row.players_analysed ?? 0) > 0;
  const conf = confidenceLevel(hasData ? (row?.avg_error ?? null) : null);

  const latestRound = row?.latest_round ?? null;
  const roundLabel = latestRound != null && latestRound > 0
    ? `Round ${latestRound}`
    : latestRound === 0
    ? "Opening Round"
    : null;

  const proofLine = (() => {
    if (!hasData || row?.avg_error == null) return null;
    const err = row.avg_error;
    const players = row?.players_analysed != null ? row.players_analysed.toLocaleString() : "—";
    return `Projections average ${err.toFixed(1)} points error across ${players} players.`;
  })();

  const metrics = [
    {
      label: "Players Analysed",
      value: hasData && row?.players_analysed != null ? row.players_analysed.toLocaleString() : "—",
      suffix: "",
      color: "text-white",
      bar: null,
    },
    {
      label: "Average Error",
      value: hasData && row?.avg_error != null ? row.avg_error.toFixed(1) : "—",
      suffix: " pts",
      color: "text-[#F5C84C]",
      bar: null,
    },
    {
      label: "Median Error",
      value: hasData && row?.median_error != null ? row.median_error.toFixed(1) : "—",
      suffix: " pts",
      color: "text-[#F5C84C]",
      bar: null,
    },
    {
      label: "Within 15 pts",
      value: hasData && row?.within_15 != null ? Math.round(row.within_15).toString() : "—",
      suffix: "%",
      color: "text-green-400",
      bar: hasData ? (row?.within_15 ?? null) : null,
      barColor: "bg-green-400",
    },
  ];

  const SIGNAL_CARDS = [
    {
      icon: Database,
      stat: hasData && row?.players_analysed != null ? `${row.players_analysed.toLocaleString()} players` : "687 players",
      desc: "Analysed every round — across all 18 AFL clubs",
    },
    {
      icon: Cpu,
      stat: "Daily updates",
      desc: "Projection model refreshed continuously as new data arrives",
    },
    {
      icon: BarChart2,
      stat: "Price vs output",
      desc: "Value scores driven by expected score relative to current price — not gut feel",
    },
    {
      icon: Sparkles,
      stat: "Real match data",
      desc: "AI explanations built from live stats — not pre-written templates",
    },
  ];

  return (
    <section className="py-10 md:py-14 bg-[#070707] border-t border-white/[0.05]">
      <div className="max-w-5xl mx-auto px-4">

        <div className="text-center mb-8">
          <span className="text-xs uppercase tracking-wide text-[#F5C84C]">
            Real Performance Data
          </span>
          <div className="mt-2"><SectionHeading>Built on Real Performance Data</SectionHeading></div>
          <p className="text-sm text-white/50 mt-3 max-w-xl mx-auto leading-relaxed">
            Every recommendation is backed by live projections, pricing inefficiencies, and player performance signals — updated continuously.
          </p>
          {proofLine && (
            <p className="text-[12px] text-white/30 mt-1.5 max-w-xl mx-auto leading-relaxed">
              {proofLine} · 2026 season
            </p>
          )}
        </div>

        <div className="grid grid-cols-2 sm:grid-cols-4 gap-3 mb-7">
          {SIGNAL_CARDS.map(({ icon: Icon, stat, desc }) => (
            <div key={stat} className="rounded-xl border border-white/[0.07] bg-[#0e0e0e] p-4 flex flex-col gap-2.5">
              <div className="w-7 h-7 rounded-lg flex items-center justify-center bg-[#F5C84C]/10 border border-[#F5C84C]/15 shrink-0">
                <Icon size={13} className="text-[#F5C84C]" />
              </div>
              <div>
                <p className="text-sm font-bold text-white leading-tight">{stat}</p>
                <p className="text-[11px] text-white/35 mt-1 leading-snug">{desc}</p>
              </div>
            </div>
          ))}
        </div>

        <div className="grid grid-cols-1 lg:grid-cols-2 gap-6">
          <div className="rounded-2xl border border-white/[0.07] bg-[#0e0e0e] overflow-hidden">
            <div className="flex items-center justify-between gap-4 px-4 py-3 border-b border-white/[0.06] bg-[#0a0a0a] flex-wrap">
              <div className="flex items-center gap-2">
                <div className="w-6 h-6 rounded-lg flex items-center justify-center bg-[#F5C84C]/10 border border-[#F5C84C]/20">
                  <Target size={13} className="text-[#F5C84C]" />
                </div>
                <span className="text-[11px] font-bold uppercase tracking-widest text-white/40">
                  {loading ? "Loading…" : "Projection Accuracy"}
                </span>
              </div>
              {!loading && (
                <div className={`inline-flex items-center gap-2 px-3 py-1 rounded-lg border ${conf.bg} ${conf.border}`}>
                  <span className="text-[9px] font-bold uppercase tracking-widest text-white/35">Confidence</span>
                  <span className={`text-[11px] font-black uppercase tracking-wider ${conf.color}`}>{conf.label}</span>
                </div>
              )}
              {loading && <div className="h-6 w-32 bg-white/[0.06] rounded-lg animate-pulse" />}
            </div>

            <div className="grid grid-cols-2 divide-x divide-y divide-neutral-800">
              {metrics.map(({ label, value, suffix, color, bar, barColor }) => (
                <div key={label} className="px-4 py-4 flex flex-col">
                  <p className="text-[10px] text-white/30 uppercase tracking-widest font-semibold leading-tight mb-1.5">
                    {label}
                  </p>
                  {loading ? (
                    <div className="h-7 w-16 bg-white/[0.06] rounded animate-pulse" />
                  ) : (
                    <>
                      <p className={`text-2xl font-extrabold tabular-nums leading-none ${color}`}>
                        {value}
                        <span className="text-sm font-bold text-white/30">
                          {value !== "—" ? suffix : ""}
                        </span>
                      </p>
                      {bar != null && barColor && (
                        <AccuracyBar pct={bar} barColor={barColor} />
                      )}
                    </>
                  )}
                </div>
              ))}
            </div>

            {!loading && hasData && roundLabel && (
              <div className="px-4 py-2 border-t border-white/[0.06] bg-[#0c0c0c]">
                <p className="text-[11px] text-white/25 text-center tracking-wide">
                  Updated through {roundLabel}
                </p>
              </div>
            )}

            {!loading && !hasData && (
              <div className="px-4 py-4 border-t border-white/[0.06] bg-[#0c0c0c]">
                <p className="text-sm text-white/30 text-center">
                  Accuracy metrics will appear after the first completed match.
                </p>
              </div>
            )}
          </div>

          <ErrorDistributionBlock row={row} loading={loading} />
        </div>

        <div className="flex items-center justify-center gap-2 text-xs text-neutral-500 mt-3">
          <Database size={11} className="shrink-0" />
          {hasData && row?.total_predictions != null
            ? <span>Model evaluated on {row.total_predictions.toLocaleString()} AFL player projections · 2026 season</span>
            : <span>Accuracy data building as rounds complete</span>
          }
        </div>
        {hasData && row?.last_updated_at && (
          <p className="text-center text-[10px] text-white/18 mt-1">
            Data updated {formatRelativeTime(row.last_updated_at)}
          </p>
        )}

        <div className="mt-6 p-5 border border-white/[0.08] rounded-xl bg-[#0d0d0d]">
          <div className="flex flex-col sm:flex-row items-start sm:items-center justify-between gap-4">
            <div>
              <p className="text-sm font-semibold text-white/70 leading-relaxed">
                This isn't opinion — it's measurable edge.
              </p>
              <p className="text-xs text-white/35 mt-1 leading-relaxed">
                See every player ranked by projection, value, and confidence — updated before each round.
              </p>
            </div>
            <Link
              to="/sports/afl/rankings"
              className="shrink-0 inline-flex items-center justify-center gap-2 bg-[#F5C84C] text-black font-bold text-sm px-5 py-2.5 rounded-xl hover:brightness-110 transition-all whitespace-nowrap"
            >
              See the Rankings
              <ArrowRight size={13} />
            </Link>
          </div>
        </div>

      </div>
    </section>
  );
}

// ─── Why Coaches Use Neeko ────────────────────────────────────────────────────

function WhyNeekoSection() {
  return (
    <section className="py-12 md:py-16 bg-[#0a0a0a] border-t border-white/[0.05]">
      <div className="max-w-5xl mx-auto px-4">
        <div className="text-center mb-8">
          <SectionLabel>Model Advantages</SectionLabel>
          <SectionHeading>WHY COACHES USE NEEKO</SectionHeading>
          <GoldDivider />
          <p className="text-base text-white/40 max-w-xl mx-auto leading-relaxed">
            Advanced modelling designed specifically for AFL Fantasy.
          </p>
        </div>

        <div className="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-4 gap-5">
          {WHY_NEEKO_BLOCKS.map(({ icon: Icon, title, desc }) => (
            <div
              key={title}
              className="bg-[#0f0f0f] border border-[#1f1f1f] rounded-xl p-5 hover:border-[#F5C84C]/25 hover:shadow-[0_0_20px_rgba(245,200,76,0.06)] transition-all"
            >
              <div className="w-10 h-10 rounded-xl bg-[#F5C84C]/10 border border-[#F5C84C]/20 flex items-center justify-center mb-4">
                <Icon size={18} className="text-[#F5C84C]" />
              </div>
              <h3 className="text-sm font-bold text-white mb-2 leading-snug">{title}</h3>
              <p className="text-xs text-white/40 leading-relaxed">{desc}</p>
            </div>
          ))}
        </div>
      </div>
    </section>
  );
}

// ─── Premium Section ──────────────────────────────────────────────────────────

const ROUND_DELIVERABLES = [
  "Updated projections for 600+ players",
  "Captain rankings",
  "Breakout alerts",
  "Trap warnings",
  "Start/Sit comparisons",
];

function PremiumSection() {
  return (
    <section className="py-12 md:py-16 bg-[#070707] border-t border-white/[0.05]">
      <div className="max-w-4xl mx-auto px-4">
        <div className="text-center mb-8">
          <SectionLabel>Pricing</SectionLabel>
          <SectionHeading>UNLOCK THE FULL EDGE</SectionHeading>
          <GoldDivider />
          <p className="text-[13px] text-[#F5C84C]/60 font-semibold mb-1">
            Less than the cost of a coffee per round.
          </p>
          <p className="text-sm text-white/40 max-w-md mx-auto leading-relaxed">
            All insights updated before AFL Fantasy round lockout.
          </p>
        </div>

        <div className="grid grid-cols-1 lg:grid-cols-2 gap-8 items-start">
          <div className="space-y-3">
            <p className="text-xs font-bold uppercase tracking-widest text-white/30 mb-4">
              What's Included
            </p>
            {NEEKO_FEATURES.map((f) => (
              <div key={f} className="flex items-center gap-3">
                <div className="w-5 h-5 rounded-full bg-[#F5C84C]/15 border border-[#F5C84C]/30 flex items-center justify-center shrink-0">
                  <Check size={10} className="text-[#F5C84C]" />
                </div>
                <span className="text-sm text-white/60">{f}</span>
              </div>
            ))}
          </div>

          <div className="flex flex-col gap-5">
            <div
              className="relative rounded-2xl p-7"
              style={{
                border: "1px solid rgba(245,200,76,0.35)",
                background: "linear-gradient(160deg, #111 0%, #0d0d0d 100%)",
                boxShadow: "0 0 40px rgba(245,200,76,0.08)",
              }}
            >
              <div className="absolute -top-3 left-1/2 -translate-x-1/2">
                <span className="bg-[#F5C84C] text-black text-[11px] font-black px-3 py-0.5 rounded-full uppercase tracking-wide">
                  Best Value
                </span>
              </div>
              <p className="text-xs font-bold uppercase tracking-widest text-[#F5C84C]/60 mb-3">Neeko+ Yearly</p>
              <div className="flex items-end gap-1.5 mb-1">
                <span className="text-4xl font-extrabold text-white">$89</span>
                <span className="text-sm text-white/35 mb-1">AUD / year</span>
              </div>
              <p className="text-xs text-[#F5C84C]/50 mb-1">Equivalent to $7.42/month · Cancel anytime</p>
              <p className="text-xs text-white/25 mb-6">$89 per year — less than $0.25 per AFL round</p>
              <Link
                to="/neeko-plus"
                className="block text-center bg-[#F5C84C] text-black font-bold text-sm py-3.5 rounded-xl hover:brightness-110 transition-all min-h-[48px] flex items-center justify-center"
              >
                <Crown size={14} className="mr-2" />
                Start Winning With Neeko+
              </Link>
            </div>

            <div className="rounded-2xl border border-white/[0.09] bg-[#0e0e0e] p-6">
              <p className="text-xs font-bold uppercase tracking-widest text-white/30 mb-3">Monthly</p>
              <div className="flex items-end gap-1.5 mb-1">
                <span className="text-3xl font-extrabold text-white">$9.99</span>
                <span className="text-sm text-white/35 mb-1">AUD / month</span>
              </div>
              <p className="text-xs text-white/25 mb-5">{NEEKO_PRICING.monthly.billingNote}</p>
              <Link
                to="/neeko-plus"
                className="block text-center border border-[#F5C84C]/40 text-[#F5C84C] font-semibold text-sm py-3 rounded-xl hover:bg-[#F5C84C]/10 transition-all min-h-[48px] flex items-center justify-center"
              >
                Start Monthly
              </Link>
            </div>
          </div>
        </div>

        <div className="mt-8 rounded-xl border border-white/[0.07] bg-[#0d0d0d] px-5 py-4">
          <p className="text-xs font-bold uppercase tracking-widest text-white/30 text-center mb-3">
            Every round, before lockout
          </p>
          <div className="flex flex-wrap justify-center gap-x-6 gap-y-2">
            {ROUND_DELIVERABLES.map((item) => (
              <div key={item} className="flex items-center gap-1.5">
                <div className="w-3.5 h-3.5 rounded-full bg-[#F5C84C]/15 border border-[#F5C84C]/30 flex items-center justify-center shrink-0">
                  <Check size={7} className="text-[#F5C84C]" />
                </div>
                <span className="text-xs text-white/40">{item}</span>
              </div>
            ))}
          </div>
        </div>

        <div className="text-center mt-4 space-y-1">
          <p className="text-xs text-white/25">Cancel anytime. No lock-in contracts.</p>
          <p className="text-xs text-white/20">All projections updated weekly during the AFL season.</p>
        </div>
      </div>
    </section>
  );
}

// ─── Edge board preview ───────────────────────────────────────────────────────

function EdgeStatRow({ label, value, valueColor }: { label: string; value: string; valueColor?: string }) {
  return (
    <div className="flex items-center justify-between py-1 border-b border-white/[0.04] last:border-0">
      <span className="text-[11px] text-white/35 font-medium">{label}</span>
      <span className={`text-[12px] font-bold tabular-nums ${valueColor ?? "text-white/70"}`}>{value}</span>
    </div>
  );
}

function EdgeCardSkeleton() {
  return (
    <div className="rounded-2xl border border-white/[0.07] bg-[#0e0e0e] p-5 animate-pulse">
      <div className="flex items-center gap-2 mb-3">
        <div className="w-9 h-9 rounded-lg bg-white/[0.06]" />
        <div className="h-3 w-24 bg-white/[0.06] rounded" />
      </div>
      <div className="h-5 w-32 bg-white/[0.08] rounded mb-1 mt-4" />
      <div className="h-3 w-20 bg-white/[0.05] rounded mb-4" />
      {[1, 2, 3, 4].map((i) => (
        <div key={i} className="flex justify-between py-1.5 border-b border-white/[0.04]">
          <div className="h-3 w-16 bg-white/[0.05] rounded" />
          <div className="h-3 w-12 bg-white/[0.05] rounded" />
        </div>
      ))}
    </div>
  );
}

type EdgeSignalType = "target" | "watch" | "avoid";

interface EdgeSignal {
  type: EdgeSignalType;
  label: string;
  desc: string;
  accentColor: string;
  icon: typeof Star;
  row: EdgeRow;
}

const SIGNAL_META: Record<EdgeSignalType, { label: string; desc: string; accentColor: string; icon: typeof Star }> = {
  target: { label: "Target",  desc: "Strong edge score — model favours this player this round.",   accentColor: "#34d399", icon: TrendingUp },
  watch:  { label: "Watch",   desc: "Neutral signal — monitor before committing to this player.",  accentColor: "#F5C84C", icon: Star },
  avoid:  { label: "Avoid",   desc: "Negative edge score — model flags elevated risk this round.", accentColor: "#f87171", icon: AlertTriangle },
};

function edgeScoreColor(score: number | null): string {
  if (score == null) return "text-white/30";
  if (score > 5)  return "text-green-400";
  if (score < -5) return "text-red-400";
  return "text-[#F5C84C]";
}

function EdgeBoardPreview() {
  const [signals, setSignals] = useState<EdgeSignal[]>([]);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    (async () => {
      const { data } = await supabase
        .from("player_rankings_cache")
        .select("player_id, player_name, team, position, projection_final, breakeven, edge_score, ai_recommendation, summary_short")
        .gte("games_played", 3)
        .gt("projection_final", 50)
        .order("edge_score", { ascending: false })
        .limit(50);

      const rows = ((data ?? []) as EdgeRow[]).filter(
        (r) => r.player_name && r.team && (r.projection_final ?? 0) > 0,
      );

      const targets = rows.filter(r => (r.edge_score ?? 0) > 5);
      const watches = rows.filter(r => (r.edge_score ?? 0) >= -5 && (r.edge_score ?? 0) <= 5);
      const avoids  = rows.filter(r => (r.edge_score ?? 0) < -5);

      const targetRow  = targets[0] ?? rows[0];
      const watchRow   = watches[0] ?? rows[Math.floor(rows.length / 2)] ?? rows[1] ?? rows[0];
      const avoidRow   = avoids[0]  ?? rows[rows.length - 1] ?? rows[0];

      const built: EdgeSignal[] = rows.length === 0 ? [] : [
        { type: "target" as EdgeSignalType, ...SIGNAL_META.target, row: targetRow },
        { type: "watch"  as EdgeSignalType, ...SIGNAL_META.watch,  row: watchRow  },
        { type: "avoid"  as EdgeSignalType, ...SIGNAL_META.avoid,  row: avoidRow  },
      ];

      setSignals(built);
      setLoading(false);
    })();
  }, []);

  return (
    <section className="py-10 md:py-14 bg-[#0a0a0a] border-t border-white/[0.05]">
      <div className="max-w-3xl mx-auto px-4">
        <SectionLabel>Edge Signals</SectionLabel>
        <SectionHeading>This Round's Edge Signals</SectionHeading>
        <GoldDivider />
        <p className="text-center text-white/40 text-sm mb-6 max-w-xl mx-auto leading-relaxed">
          Model-derived signals from the top 50 players — updated before every round lockout.
        </p>

        <div className="grid grid-cols-1 sm:grid-cols-3 gap-4">
          {loading
            ? [0, 1, 2].map((i) => <EdgeCardSkeleton key={i} />)
            : signals.length > 0
              ? signals.map((signal) => {
                  const { label, desc, accentColor, icon: Icon, row, type } = signal;
                  const scoreColor = edgeScoreColor(row.edge_score);

                  return (
                    <div
                      key={type}
                      className="rounded-2xl bg-[#0e0e0e] p-5 hover:scale-[1.01] transition-all"
                      style={{ border: `1px solid ${accentColor}25` }}
                    >
                      <div className="flex items-center gap-2 mb-4">
                        <div
                          className="w-9 h-9 rounded-lg flex items-center justify-center shrink-0"
                          style={{ background: `${accentColor}15`, border: `1px solid ${accentColor}30` }}
                        >
                          <Icon size={16} style={{ color: accentColor }} />
                        </div>
                        <span className="text-xs font-bold uppercase tracking-widest" style={{ color: accentColor }}>
                          {label}
                        </span>
                      </div>

                      <p className="text-base font-bold text-white leading-tight mb-0.5">{row.player_name}</p>
                      <p className="text-[11px] text-white/35 mb-1">{row.team}{row.position ? ` · ${row.position}` : ""}</p>
                      {row.summary_short && (
                        <p className="text-[10px] text-white/30 mb-3 leading-snug italic">{row.summary_short}</p>
                      )}
                      {!row.summary_short && (
                        <p className="text-[10px] text-white/20 mb-3 leading-snug">{desc}</p>
                      )}

                      <div>
                        {row.projection_final != null && (
                          <EdgeStatRow label="Projection" value={`${Math.round(row.projection_final)} pts`} valueColor="text-[#F5C84C]" />
                        )}
                        {row.breakeven != null && (
                          <EdgeStatRow label="Breakeven" value={`${Math.round(row.breakeven)} pts`} valueColor="text-white/60" />
                        )}
                        {row.edge_score != null && (
                          <EdgeStatRow label="Edge Score" value={row.edge_score.toFixed(1)} valueColor={scoreColor} />
                        )}
                        {row.ai_recommendation && (
                          <EdgeStatRow label="Signal" value={row.ai_recommendation.replace(/_/g, " ")} valueColor="text-white/40" />
                        )}
                      </div>
                    </div>
                  );
                })
              : (
                <div className="col-span-3 rounded-2xl border border-white/[0.07] bg-[#0e0e0e] p-8 text-center">
                  <p className="text-sm text-white/30">Edge signals will appear once round data is processed.</p>
                </div>
              )
          }
        </div>

        <p className="text-center text-white/25 text-xs mt-4">
          Full edge board includes additional signals, matchup analysis and AI breakdowns.
        </p>

        <div className="mt-3 flex justify-center">
          <Link
            to="/neeko-plus"
            className="inline-flex items-center justify-center gap-2 bg-[#F5C84C] text-black font-bold text-sm px-7 py-3.5 rounded-xl hover:brightness-110 transition-all min-h-[48px]"
          >
            <Crown size={14} />
            Unlock All Edge Signals
          </Link>
        </div>
      </div>
    </section>
  );
}

// ─── Who It's For ─────────────────────────────────────────────────────────────

function WhoForSection() {
  return (
    <section className="py-10 md:py-14 bg-[#0a0a0a] border-t border-white/[0.05]">
      <div className="max-w-4xl mx-auto px-4">
        <SectionLabel>Who It's For</SectionLabel>
        <SectionHeading>Built For Serious AFL Fantasy Coaches</SectionHeading>
        <GoldDivider />

        <div className="grid grid-cols-1 sm:grid-cols-3 gap-4 md:gap-5 mt-6">
          {WHO_FOR.map(({ icon: Icon, title, desc }) => (
            <div
              key={title}
              className="rounded-2xl border border-white/[0.07] bg-[#0e0e0e] p-5 hover:border-white/[0.12] transition-all"
            >
              <div className="flex items-center justify-center w-10 h-10 rounded-xl bg-white/[0.05] border border-white/[0.08] mb-4">
                <Icon size={18} className="text-white/50" />
              </div>
              <h3 className="text-base font-bold text-white mb-2">{title}</h3>
              <p className="text-sm text-white/40 leading-relaxed">{desc}</p>
            </div>
          ))}
        </div>
      </div>
    </section>
  );
}

// ─── Problem Section ──────────────────────────────────────────────────────────

function ProblemSection() {
  const leftItems = [
    "Captain based on gut feel",
    "Trades based on hype",
    "Matchups ignored",
    "Value misunderstood",
  ];

  const rightItems = [
    "Data-driven captain signals",
    "Breakout probability modelling",
    "Opponent-adjusted projections",
    "Value engine detecting mispriced players",
  ];

  return (
    <section className="py-10 md:py-14 bg-[#070707] border-t border-white/[0.05]">
      <div className="max-w-4xl mx-auto px-4">
        <SectionLabel>Competitive Advantage</SectionLabel>
        <SectionHeading>Why Most AFL Fantasy Coaches Lose</SectionHeading>
        <GoldDivider />

        <div className="mt-6 grid grid-cols-1 sm:grid-cols-2 gap-5">
          <div className="rounded-2xl border border-white/[0.06] bg-[#0d0d0d] p-5">
            <p className="text-xs font-bold uppercase tracking-widest text-white/25 mb-5">
              Typical Fantasy Decisions
            </p>
            <ul className="space-y-3">
              {leftItems.map((item) => (
                <li key={item} className="flex items-start gap-3">
                  <span className="mt-1 w-4 h-4 rounded-full border border-white/15 flex items-center justify-center shrink-0">
                    <span className="w-1.5 h-1.5 rounded-full bg-white/20" />
                  </span>
                  <span className="text-sm text-white/30 leading-relaxed">{item}</span>
                </li>
              ))}
            </ul>
          </div>

          <div
            className="rounded-2xl p-5"
            style={{
              border: "1px solid rgba(245,200,76,0.30)",
              background: "linear-gradient(160deg, #131313 0%, #0e0e0e 100%)",
              boxShadow: "0 0 36px rgba(245,200,76,0.08)",
            }}
          >
            <p className="text-xs font-bold uppercase tracking-widest text-[#F5C84C]/60 mb-5">
              Neeko Data Advantage
            </p>
            <ul className="space-y-3">
              {rightItems.map((item) => (
                <li key={item} className="flex items-start gap-3">
                  <div className="mt-1 w-4 h-4 rounded-full bg-[#F5C84C]/15 border border-[#F5C84C]/30 flex items-center justify-center shrink-0">
                    <Check size={8} className="text-[#F5C84C]" />
                  </div>
                  <span className="text-sm text-white/75 leading-relaxed">{item}</span>
                </li>
              ))}
            </ul>
          </div>
        </div>

        <div className="mt-6 flex justify-center">
          <Link
            to="/neeko-plus"
            className="inline-flex items-center justify-center gap-2 bg-[#F5C84C] text-black font-bold text-sm px-7 py-3.5 rounded-xl hover:brightness-110 transition-all shadow-[0_4px_30px_rgba(245,200,76,0.2)] min-h-[48px]"
          >
            <Crown size={14} />
            Start Winning With Neeko+
          </Link>
        </div>
      </div>
    </section>
  );
}

// ─── Outcome Proof ────────────────────────────────────────────────────────────

function accuracyBadge(tier: "ELITE" | "STRONG" | undefined) {
  if (tier === "ELITE") {
    return {
      label:     "ELITE ACCURACY",
      textColor: "text-green-400",
      bg:        "bg-green-400/10",
      border:    "border-green-400/30",
    };
  }
  return {
    label:     "STRONG ACCURACY",
    textColor: "text-[#F5C84C]",
    bg:        "bg-[#F5C84C]/10",
    border:    "border-[#F5C84C]/30",
  };
}

function OutcomeProofSection() {
  const [rows, setRows]       = useState<AccuracyExampleRow[]>([]);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    (async () => {
      const { data: raw } = await supabase
        .rpc("get_projection_accuracy_examples");
      setRows((raw ?? []) as AccuracyExampleRow[]);
      setLoading(false);
    })();
  }, []);

  const skeletons = Array.from({ length: 3 });

  return (
    <section className="py-10 md:py-14 bg-[#070707] border-t border-white/[0.05]">
      <div className="max-w-4xl mx-auto px-4">
        <div className="text-center mb-8">
          <SectionLabel>Projection Accuracy</SectionLabel>
          <SectionHeading>Real Projection Accuracy</SectionHeading>
          <GoldDivider />
          <p className="text-sm text-white/40 max-w-lg mx-auto leading-relaxed">
            Top-ranked players from the latest round where projections landed within 10 points of the final AFL Fantasy score.
          </p>
        </div>

        <div className="grid grid-cols-1 sm:grid-cols-3 gap-5">
          {loading
            ? skeletons.map((_, i) => (
                <div key={i} className="rounded-2xl border border-white/[0.07] bg-[#0e0e0e] p-5 animate-pulse">
                  <div className="h-4 w-32 bg-white/[0.08] rounded mb-2" />
                  <div className="h-3 w-24 bg-white/[0.05] rounded mb-4" />
                  <div className="h-3 w-28 bg-white/[0.05] rounded mb-1.5" />
                  <div className="h-3 w-28 bg-white/[0.05] rounded mb-3" />
                  <div className="h-5 w-28 bg-green-400/10 rounded" />
                </div>
              ))
            : rows.length > 0
              ? rows.map((r, i) => {
                  const err    = Number(r.error);
                  const errStr = err < 1 ? "< 1 pt" : `${Math.round(err)} pt${Math.round(err) === 1 ? "" : "s"}`;
                  const badge  = accuracyBadge(r.accuracy_tier);
                  return (
                    <div
                      key={`${r.player_name}-${i}`}
                      className="rounded-2xl border border-white/[0.07] bg-[#0e0e0e] p-5 hover:border-white/[0.12] transition-all"
                    >
                      <div className="flex items-start justify-between mb-0.5">
                        <p className="text-base font-bold text-white leading-tight">{r.player_name}</p>
                        {r.neeko_rank != null && (
                          <span className="text-[10px] font-semibold text-[#F5C84C]/60 tabular-nums shrink-0 ml-2">#{r.neeko_rank}</span>
                        )}
                      </div>
                      <p className="text-xs text-white/35 mb-4">{r.team_name}</p>

                      <div className="space-y-2 mb-4">
                        <div className="flex items-center justify-between">
                          <span className="text-[11px] text-white/30 uppercase tracking-widest font-semibold">Projection</span>
                          <span className="text-sm font-bold text-[#F5C84C]">{r.projection} pts</span>
                        </div>
                        <div className="flex items-center justify-between">
                          <span className="text-[11px] text-white/30 uppercase tracking-widest font-semibold">Actual</span>
                          <span className="text-sm font-bold text-white">{r.actual_score} pts</span>
                        </div>
                        <div className="flex items-center justify-between">
                          <span className="text-[11px] text-white/30 uppercase tracking-widest font-semibold">Error</span>
                          <span className="text-xs font-bold text-white/50">{errStr} off</span>
                        </div>
                      </div>

                      <div className={`inline-flex items-center gap-1.5 px-2.5 py-1 rounded-lg border ${badge.bg} ${badge.border}`}>
                        <Check size={9} className={badge.textColor} />
                        <span className={`text-[10px] font-bold uppercase tracking-wide ${badge.textColor}`}>{badge.label}</span>
                      </div>
                    </div>
                  );
                })
              : (
                <div className="col-span-3 rounded-2xl border border-white/[0.07] bg-[#0e0e0e] p-8 text-center">
                  <p className="text-sm font-semibold text-white/30">Accuracy data building...</p>
                  <p className="text-xs text-white/18 mt-1">Examples will appear once round results are processed.</p>
                </div>
              )
          }
        </div>

        <p className="text-center text-[11px] text-white/20 mt-5 tracking-wide">
          Based on completed 2026 AFL season rounds. Individual results vary.
        </p>
      </div>
    </section>
  );
}


// ─── Rankings helpers ─────────────────────────────────────────────────────────

function valueLabel(tag: string | null, score: number | null): { label: string; textColor: string; bg: string; border: string } {
  const t = (tag ?? "").toUpperCase();
  if (t.includes("ELITE") || t.includes("STRONG"))    return { label: "STRONG",    textColor: "text-green-400",  bg: "bg-green-400/10",  border: "border-green-400/30" };
  if (t.includes("SOLID") || t.includes("FAIR"))       return { label: "FAIR",       textColor: "text-white/50",   bg: "bg-white/5",       border: "border-white/10" };
  if (t.includes("LOW") || t.includes("OVERPRICED"))   return { label: "LOW VALUE",  textColor: "text-orange-400", bg: "bg-orange-400/10", border: "border-orange-400/30" };
  if (score == null)                                    return { label: "—",          textColor: "text-white/30",   bg: "bg-white/5",       border: "border-white/10" };
  if (score >= 4.0)                                     return { label: "STRONG",    textColor: "text-green-400",  bg: "bg-green-400/10",  border: "border-green-400/30" };
  if (score >= 1.7)                                     return { label: "FAIR",       textColor: "text-white/50",   bg: "bg-white/5",       border: "border-white/10" };
  return                                                       { label: "LOW VALUE",  textColor: "text-orange-400", bg: "bg-orange-400/10", border: "border-orange-400/30" };
}

function RankingsPreview() {
  const [rows, setRows] = useState<RankingRow[]>([]);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    (async () => {
      const { data } = await supabase
        .from("player_rankings_cache")
        .select("player_id, player_name, team, position, projection_final, ai_recommendation, summary_short, value_score, value_tag")
        .gte("games_played", 3)
        .gt("projection_final", 50)
        .order("projection_final", { ascending: false })
        .limit(5);
      setRows((data ?? []) as RankingRow[]);
      setLoading(false);
    })();
  }, []);

  return (
    <section className="py-10 md:py-14 bg-[#070707] border-t border-white/[0.05]">
      <div className="max-w-4xl mx-auto px-4">
        <SectionLabel>Rankings Preview</SectionLabel>
        <SectionHeading>This Week's Top Rankings</SectionHeading>
        <GoldDivider />
        <p className="text-center text-white/40 text-sm mb-6 max-w-lg mx-auto">
          600+ players ranked every round using the Neeko projection engine.
        </p>

        {/* Desktop table */}
        <div className="hidden md:block rounded-2xl border border-white/[0.07] overflow-hidden">
          <div className="grid grid-cols-[2rem_1fr_5rem_7rem] gap-x-4 px-5 py-3 text-[10px] font-semibold text-white/25 uppercase tracking-widest border-b border-white/[0.06] bg-[#0a0a0a]">
            <span>#</span>
            <span>Player</span>
            <span className="text-center text-[#F5C84C]/60">Projection</span>
            <span className="text-right">Value</span>
          </div>

          {loading
            ? Array.from({ length: 5 }).map((_, i) => (
                <div key={i} className="animate-pulse grid grid-cols-[2rem_1fr_5rem_7rem] gap-x-4 px-5 py-4 border-b border-white/[0.04] bg-[#0c0c0c] last:border-0">
                  {Array.from({ length: 4 }).map((__, j) => (
                    <div key={j} className="h-4 bg-white/[0.06] rounded" />
                  ))}
                </div>
              ))
            : rows.length > 0
              ? (
                <>
                  {rows.map((row, idx) => {
                    const val  = valueLabel(row.value_tag, row.value_score);
                    return (
                      <div key={row.player_id ?? idx} className="grid grid-cols-[2rem_1fr_5rem_7rem] gap-x-4 px-5 py-3.5 border-b border-white/[0.04] bg-[#0c0c0c] hover:bg-[#111] transition-colors last:border-0 items-center">
                        <span className="text-xs text-white/25 font-mono">{idx + 1}</span>
                        <div className="min-w-0">
                          <p className="text-sm font-bold text-white truncate leading-tight">{row.player_name}</p>
                          {row.position && <p className="text-[10px] text-white/30 leading-tight">{row.position}</p>}
                        </div>
                        <span className="text-sm font-bold text-[#F5C84C] text-center tabular-nums">
                          {row.projection_final != null ? Math.round(row.projection_final) : "—"}
                        </span>
                        <div className="flex justify-end">
                          {val.label === "—"
                            ? <span className="text-xs text-white/30">—</span>
                            : (
                              <span className={`inline-flex items-center px-2.5 py-0.5 rounded-full text-[11px] font-bold border ${val.bg} ${val.border} ${val.textColor}`}>
                                {val.label}
                              </span>
                            )
                          }
                        </div>
                      </div>
                    );
                  })}

                  {[6, 7].map((rank) => (
                    <div key={rank} className="grid grid-cols-[2rem_1fr_5rem_7rem] gap-x-4 px-5 py-3.5 border-b border-white/[0.04] bg-[#0c0c0c] last:border-0 items-center select-none">
                      <span className="text-xs text-white/15 font-mono">{rank}</span>
                      <div className="flex items-center gap-2">
                        <Lock size={11} className="text-white/20 shrink-0" />
                        <span className="text-sm font-bold text-white/20 blur-[3px]">Premium Player</span>
                        <span className="inline-flex items-center px-1.5 py-0.5 rounded-md bg-[#F5C84C]/10 border border-[#F5C84C]/20 text-[9px] font-bold text-[#F5C84C]/60 uppercase tracking-wide shrink-0">
                          Neeko+
                        </span>
                      </div>
                      <span className="text-xs text-white/15 text-center blur-[3px]">—</span>
                      <span className="text-xs text-white/15 text-right blur-[3px]">—</span>
                    </div>
                  ))}
                </>
              )
              : (
                <div className="px-5 py-8 text-center text-sm text-white/25 bg-[#0c0c0c]">
                  Rankings will be available when round data is processed.
                </div>
              )
          }
        </div>

        {/* Mobile table */}
        <div className="md:hidden rounded-2xl border border-white/[0.07] overflow-hidden">
          <div className="grid grid-cols-[2rem_1fr_4.5rem_5rem] gap-x-3 px-4 py-3 text-[10px] font-semibold text-white/25 uppercase tracking-widest border-b border-white/[0.06] bg-[#0a0a0a]">
            <span>#</span>
            <span>Player</span>
            <span className="text-center text-[#F5C84C]/60">Proj.</span>
            <span className="text-right">Value</span>
          </div>

          {loading
            ? Array.from({ length: 5 }).map((_, i) => (
                <div key={i} className="animate-pulse grid grid-cols-[2rem_1fr_4.5rem_5rem] gap-x-3 px-4 py-4 border-b border-white/[0.04] bg-[#0c0c0c] last:border-0">
                  {Array.from({ length: 4 }).map((__, j) => (
                    <div key={j} className="h-4 bg-white/[0.06] rounded" />
                  ))}
                </div>
              ))
            : rows.length > 0
              ? (
                <>
                  {rows.map((row, idx) => {
                    const val = valueLabel(row.value_tag, row.value_score);
                    return (
                      <div key={row.player_id ?? idx} className="grid grid-cols-[2rem_1fr_4.5rem_5rem] gap-x-3 px-4 py-3.5 border-b border-white/[0.04] bg-[#0c0c0c] hover:bg-[#111] transition-colors last:border-0 items-center">
                        <span className="text-xs text-white/25 font-mono">{idx + 1}</span>
                        <span className="text-sm font-bold text-white truncate">{row.player_name}</span>
                        <span className="text-sm font-bold text-[#F5C84C] text-center tabular-nums">
                          {row.projection_final != null ? Math.round(row.projection_final) : "—"}
                        </span>
                        <div className="flex justify-end">
                          {val.label === "—"
                            ? <span className="text-xs text-white/30">—</span>
                            : (
                              <span className={`inline-flex items-center px-1.5 py-0.5 rounded-full text-[10px] font-bold border ${val.bg} ${val.border} ${val.textColor}`}>
                                {val.label}
                              </span>
                            )
                          }
                        </div>
                      </div>
                    );
                  })}

                  {[6, 7].map((rank) => (
                    <div key={rank} className="grid grid-cols-[2rem_1fr_4.5rem_5rem] gap-x-3 px-4 py-3.5 border-b border-white/[0.04] bg-[#0c0c0c] last:border-0 items-center select-none">
                      <span className="text-xs text-white/15 font-mono">{rank}</span>
                      <div className="flex items-center gap-1.5">
                        <Lock size={10} className="text-white/20 shrink-0" />
                        <span className="text-sm font-bold text-white/20 blur-[3px] truncate">Premium</span>
                        <span className="inline-flex items-center px-1 py-0.5 rounded bg-[#F5C84C]/10 border border-[#F5C84C]/20 text-[9px] font-bold text-[#F5C84C]/60 uppercase shrink-0">+</span>
                      </div>
                      <span className="text-xs text-white/15 text-center blur-[3px]">—</span>
                      <span className="text-xs text-white/15 text-right blur-[3px]">—</span>
                    </div>
                  ))}
                </>
              )
              : (
                <div className="px-4 py-8 text-center text-sm text-white/25 bg-[#0c0c0c]">
                  Rankings will be available when round data is processed.
                </div>
              )
          }
        </div>

        <div className="mt-4 rounded-xl border border-[#F5C84C]/20 bg-[#0d0d0d] px-5 py-4 flex flex-col sm:flex-row items-center justify-between gap-4"
          style={{ boxShadow: "0 0 24px rgba(245,200,76,0.04)" }}
        >
          <div className="flex items-center gap-3">
            <div className="w-8 h-8 rounded-lg bg-[#F5C84C]/10 border border-[#F5C84C]/20 flex items-center justify-center shrink-0">
              <Lock size={14} className="text-[#F5C84C]" />
            </div>
            <div>
              <p className="text-sm font-bold text-white leading-tight">Unlock full rankings with Neeko+</p>
              <p className="text-[11px] text-white/35 leading-tight mt-0.5">600+ players · Updated before every lockout</p>
            </div>
          </div>
          <Link
            to="/neeko-plus"
            className="shrink-0 inline-flex items-center justify-center gap-2 bg-[#F5C84C] text-black font-bold text-sm px-6 py-2.5 rounded-xl hover:brightness-110 transition-all min-h-[44px] w-full sm:w-auto"
          >
            <Crown size={13} />
            Unlock Full Rankings
          </Link>
        </div>
      </div>
    </section>
  );
}

// ─── Main page ────────────────────────────────────────────────────────────────

export default function Index() {
  const { isPremium } = useAuth();

  useEffect(() => {
    document.title = "Neeko Sports Stats — AI AFL Fantasy Intelligence";
    const metaDesc = document.querySelector('meta[name="description"]');
    if (metaDesc) metaDesc.setAttribute("content", "AI-powered AFL fantasy projections, rankings, and trade insights. Captain picks, breakout alerts and trade signals updated every round.");
    const ogTitle = document.querySelector('meta[property="og:title"]');
    if (ogTitle) ogTitle.setAttribute("content", "Neeko Sports Stats — AI AFL Fantasy Intelligence");
    const ogDesc = document.querySelector('meta[property="og:description"]');
    if (ogDesc) ogDesc.setAttribute("content", "AI-powered AFL fantasy projections, rankings, and trade insights.");
    return () => {
      document.title = "Neeko Sports Stats — AI AFL Fantasy Projections";
    };
  }, []);

  return (
    <div className="min-h-screen bg-[#070707] text-white pb-[80px] sm:pb-0">

      {/* ── HERO ──────────────────────────────────────────────────────────────── */}
      <section className="relative overflow-hidden min-h-[72vh] flex items-center">
        <div
          className="absolute inset-0"
          style={{
            backgroundImage: "url(/hero.jpg)",
            backgroundSize: "cover",
            backgroundPosition: "center 65%",
          }}
        />
        <div
          className="absolute inset-0"
          style={{
            background: "linear-gradient(to bottom, rgba(0,0,0,0.65) 0%, rgba(0,0,0,0.75) 60%, #070707 100%)",
          }}
        />

        <div className="relative z-10 w-full max-w-4xl mx-auto px-5 py-16 md:py-24 text-center">
          <div className="inline-flex items-center gap-2 px-3.5 py-1.5 rounded-full border border-[#F5C84C]/35 bg-[#F5C84C]/10 text-[#F5C84C] text-[11px] font-bold uppercase tracking-widest mb-7">
            AFL 2026 Season Live
          </div>

          <h1 className="text-4xl sm:text-5xl md:text-[5.5rem] font-extrabold leading-[1.08] tracking-tight mb-6">
            Stop Guessing. Start Winning AFL Fantasy.
          </h1>

          <p className="text-base md:text-xl text-neutral-400 font-medium mb-10 max-w-2xl mx-auto leading-relaxed px-1">
            Neeko combines projections, matchup difficulty and value modelling to help serious AFL Fantasy coaches make smarter weekly decisions.
          </p>

          <div className="flex flex-col gap-3 sm:flex-row sm:justify-center sm:items-center px-2 sm:px-0">
            {!isPremium && (
              <Link
                to="/neeko-plus"
                className="flex items-center justify-center gap-2 bg-[#F5C84C] text-black font-bold text-sm px-8 rounded-xl hover:brightness-110 transition-all shadow-[0_4px_30px_rgba(245,200,76,0.25)] min-h-[52px] w-full sm:w-auto"
              >
                <Crown size={15} />
                Start Winning With Neeko+
              </Link>
            )}
            <Link
              to="/sports/afl/rankings"
              className={`flex items-center justify-center gap-2 font-semibold text-sm px-8 rounded-xl transition-all min-h-[52px] w-full sm:w-auto ${
                isPremium
                  ? "bg-[#F5C84C] text-black hover:brightness-110"
                  : "border border-white/15 text-white/70 hover:text-white hover:border-white/30 bg-transparent"
              }`}
            >
              View Free Rankings
              <ArrowRight size={14} />
            </Link>
          </div>

          <div className="mt-5 flex flex-col sm:flex-row items-center justify-center gap-3 sm:gap-6">
            <p className="text-[12px] text-white/30 font-medium tracking-wide">
              Updated before every AFL Fantasy round lockout
            </p>
            <span className="hidden sm:block text-white/15">·</span>
            <p className="text-[12px] text-white/30 font-medium tracking-wide">
              600+ players ranked every week
            </p>
          </div>
        </div>
      </section>

      {/* ── SECTION 2: RANKINGS PREVIEW ───────────────────────────────────────── */}
      <RankingsPreview />

      {/* ── SECTION 3: EDGE SIGNALS PREVIEW ──────────────────────────────────── */}
      <EdgeBoardPreview />

      {/* ── SECTION 3B: MARKET WATCH SAMPLE ──────────────────────────────────── */}
      <LandingMarketWatchSample />

      {/* ── SECTION 4: FEATURE CARDS / TOOLKIT ───────────────────────────────── */}
      <FeatureCards />

      {/* ── SECTION 5: PROBLEM / WHY COACHES LOSE ────────────────────────────── */}
      <ProblemSection />

      {/* ── SECTION 6: MODEL ACCURACY ─────────────────────────────────────────── */}
      <ModelAccuracySection />

      {/* ── SECTION 7: PROJECTION ACCURACY ───────────────────────────────────── */}
      <OutcomeProofSection />

      {/* ── SECTION 8: WHO IT'S FOR ───────────────────────────────────────────── */}
      <WhoForSection />

      {/* ── FINAL CTA ─────────────────────────────────────────────────────────── */}
      <section className="py-12 md:py-16 bg-[#0a0a0a] border-t border-white/[0.05]">
        <div className="max-w-xl mx-auto px-5 text-center">
          <p className="text-[12px] text-[#F5C84C]/60 font-semibold uppercase tracking-widest mb-3">
            Updated before every AFL Fantasy round lockout
          </p>
          <h2 className="text-2xl md:text-4xl font-extrabold mb-3 leading-tight">
            Start Winning More AFL Fantasy Matchups
          </h2>
          <p className="text-white/40 text-sm mb-5 max-w-sm mx-auto leading-relaxed">
            Use data instead of guesswork.
          </p>
          <div className="flex flex-col sm:flex-row gap-3 justify-center items-center">
            <Link
              to="/neeko-plus"
              className="flex items-center justify-center gap-2 bg-[#F5C84C] text-black font-bold text-sm px-8 py-3.5 rounded-xl hover:brightness-110 transition-all min-h-[52px] w-full sm:w-auto shadow-[0_4px_30px_rgba(245,200,76,0.2)]"
            >
              <Crown size={14} />
              Start Winning With Neeko+
            </Link>
            <Link
              to="/sports/afl/rankings"
              className="flex items-center justify-center gap-2 border border-white/15 text-white/70 hover:text-white hover:border-white/30 font-semibold text-sm px-8 py-3.5 rounded-xl transition-all min-h-[52px] w-full sm:w-auto"
            >
              View Free Rankings
              <ArrowRight size={14} />
            </Link>
          </div>
          <p className="text-[12px] text-white/25 mt-4">
            Neeko+ — $10 per month. <span className="text-white/15">Cancel anytime.</span>
          </p>
        </div>
      </section>

      {/* ── MOBILE STICKY UPGRADE BAR ─────────────────────────────────────────── */}
      {!isPremium && <MobileUpgradeBar />}

      {/* ── FOOTER ────────────────────────────────────────────────────────────── */}
      <footer className="border-t border-white/[0.05] bg-[#070707] py-8">
        <div className="max-w-4xl mx-auto px-4">
          <div className="flex flex-col sm:flex-row justify-between items-center gap-4">
            <p className="text-xs text-white/25">
              © {new Date().getFullYear()} Neeko Sports Stats. All rights reserved.
            </p>
            <div className="flex gap-5 text-xs">
              {FOOTER_LINKS.map((l) => (
                <Link key={l.to} to={l.to} className="text-white/25 hover:text-white/60 transition-colors">
                  {l.label}
                </Link>
              ))}
            </div>
          </div>
        </div>
      </footer>

    </div>
  );
}
