/*
  # Fix ai_validation_passed backfill

  ## Problem
  487 rows in afl.player_rankings_cache have ai_validation_passed = false despite containing
  valid AI content. Root cause: AI text was generated by older prompt versions that used
  "suggests" and "indicates" — words that were later added to the validator's weakPhrases list.
  These words are now banned in the system prompt so new AI won't produce them, but existing
  valid content was incorrectly flagged.

  ## Fix
  Backfill ai_validation_passed = true for all rows that:
  1. Have real AI content (summary_short and summary_long both present and non-empty)
  2. Do NOT contain actually harmful banned phrases (could, might, " may ", this round, overall,)
  3. Have a summary_short that contains a number (required quality gate)

  Rows that contain genuinely banned phrases remain false and will be regenerated naturally
  by the AI regen pipeline.
*/

UPDATE afl.player_rankings_cache
SET ai_validation_passed = true
WHERE ai_validation_passed = false
  AND summary_short IS NOT NULL AND summary_short != ''
  AND summary_long  IS NOT NULL AND summary_long  != ''
  AND summary_short ~ '\d'
  AND lower(summary_short || ' ' || summary_long) NOT LIKE '%could%'
  AND lower(summary_short || ' ' || summary_long) NOT LIKE '%might%'
  AND lower(summary_short || ' ' || summary_long) NOT LIKE '% may %'
  AND lower(summary_short || ' ' || summary_long) NOT LIKE '% may,%'
  AND lower(summary_short || ' ' || summary_long) NOT LIKE '% may.%'
  AND lower(summary_short || ' ' || summary_long) NOT LIKE '%this round%'
  AND lower(summary_short || ' ' || summary_long) NOT LIKE '%overall,%'
  AND lower(summary_short || ' ' || summary_long) NOT LIKE '%solid option%';
