/*
  # Add AI Prompt Version and Validation Tracking

  ## Purpose
  Add observability columns to track which prompt version generated each AI output,
  whether the output passed validation, and when it was generated. These fields
  enable:
  - Targeted invalidation when prompt version changes
  - Audit trail for AI quality issues
  - Selective forced regen of rows generated by old/bad prompts

  ## Changes

  ### afl.player_rankings_cache (primary writeback target)
  - `ai_prompt_version` (text) — stores prompt version string e.g. "generate-player-ai-v4"
  - `ai_validation_passed` (boolean) — true if output cleared all validation checks
  - `ai_generated_at` (timestamptz) — explicit generation timestamp (distinct from updated_at)

  ## Notes
  - All columns are nullable to allow existing rows without regeneration
  - No data loss risk — additive only
*/

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.columns
    WHERE table_schema = 'afl' AND table_name = 'player_rankings_cache' AND column_name = 'ai_prompt_version'
  ) THEN
    ALTER TABLE afl.player_rankings_cache ADD COLUMN ai_prompt_version text;
  END IF;

  IF NOT EXISTS (
    SELECT 1 FROM information_schema.columns
    WHERE table_schema = 'afl' AND table_name = 'player_rankings_cache' AND column_name = 'ai_validation_passed'
  ) THEN
    ALTER TABLE afl.player_rankings_cache ADD COLUMN ai_validation_passed boolean;
  END IF;

  IF NOT EXISTS (
    SELECT 1 FROM information_schema.columns
    WHERE table_schema = 'afl' AND table_name = 'player_rankings_cache' AND column_name = 'ai_generated_at'
  ) THEN
    ALTER TABLE afl.player_rankings_cache ADD COLUMN ai_generated_at timestamptz;
  END IF;
END $$;

CREATE INDEX IF NOT EXISTS idx_player_rankings_cache_ai_prompt_version
  ON afl.player_rankings_cache (ai_prompt_version);

CREATE INDEX IF NOT EXISTS idx_player_rankings_cache_ai_generated_at
  ON afl.player_rankings_cache (ai_generated_at);
