/*
  # Add prompt_version to afl.ai_team_summaries

  Adds a prompt_version column to track which prompt generated each summary.
  Used by generate-team-ai-summaries edge function to skip fresh summaries
  generated by the current prompt version.
*/

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.columns
    WHERE table_schema = 'afl' AND table_name = 'ai_team_summaries' AND column_name = 'prompt_version'
  ) THEN
    ALTER TABLE afl.ai_team_summaries ADD COLUMN prompt_version text DEFAULT NULL;
  END IF;
END $$;
