/*
  # Expose signal_tag in public.player_rankings_cache view

  ## Summary
  Drops and recreates public.player_rankings_cache to include signal_tag column.
  This is the PostgREST-accessible view all frontend pages query directly.
*/

DROP VIEW IF EXISTS public.player_rankings_cache CASCADE;

CREATE VIEW public.player_rankings_cache AS
SELECT
  player_id,
  player_name,
  team,
  team_name,
  "position",
  position_group,
  projection_final,
  projection,
  ceiling,
  floor,
  ceiling_estimate,
  floor_estimate,
  consistency,
  form_score,
  neeko_rating,
  price,
  value_score,
  value_tag,
  value_tier,
  signal,
  summary,
  analysis,
  projection_confidence,
  risk_rating,
  matchup_rating,
  upside_rating,
  captain_score,
  captain_rating,
  ai_recommendation,
  signal_tag,
  recommendation_color,
  recommendation_short,
  recommendation_why,
  ai_summary,
  ai_updated_at,
  consistency_tier,
  total_count,
  cached_at,
  created_at,
  best_value_score,
  games_played,
  matchup_multiplier,
  matchup_label,
  neeko_rating_raw,
  neeko_rating_scaled,
  upside_pct,
  recommendation_strength,
  start_sit_decision,
  edge_score,
  edge_tier,
  market_watch_category,
  ai_prompt_version,
  ai_validation_passed,
  ai_generated_at,
  cache_snapshot_id,
  ai_cache_snapshot_id,
  confidence_label,
  pipeline_snapshot_id,
  status,
  is_available,
  prev_price,
  price_change,
  price_change_pct,
  bye_round,
  is_bye,
  bye_next_round,
  team_id,
  summary_short,
  summary_long,
  manual_status,
  breakeven,
  edge_c_base,
  edge_c_form,
  edge_c_ceiling,
  edge_c_opponent,
  edge_c_venue,
  edge_c_role,
  edge_c_momentum,
  edge_c_breakout,
  edge_c_risk
FROM afl.player_rankings_cache;

GRANT SELECT ON public.player_rankings_cache TO anon, authenticated;
