export interface CommandCenterStatus {
  rankings_cache_rows: number;
  rankings_cache_refreshed_at: string | null;
  rankings_cache_status: string;
  pipeline_status: string | null;
  pipeline_last_run: string | null;
  pipeline_finished_at: string | null;
  pipeline_health: string;
  ai_analysis_rows: number;
  ai_missing_players: number;
  ai_players_excluded: number | null;
  ai_last_updated: string | null;
  ai_last_generation: string | null;
  reco_rows: number;
  reco_last_updated: string | null;
  ai_health: string;
  queue_pending: number;
  queue_processing: number;
  queue_complete: number;
  queue_failed: number;
  queue_health: string;
  market_watch_last_refresh: string | null;
  market_watch_quality: string | null;
  market_watch_health: string;
  cron_active_count: number;
  cron_inactive_count: number;
  cron_failed_count: number;
  cron_health: string;
  recent_error_count: number;
  system_logs_last_event_at: string | null;
  logs_health: string;
  fantasy_price_last_updated: string | null;
  fantasy_matched_count: number | null;
  fantasy_unmatched_count: number | null;
  accuracy_last_updated: string | null;
  edge_board_last_refreshed: string | null;
  edge_board_rows: number | null;
}
